import {
  ConcurrencyAndTasks,
  ControlFlow,
  CurrentLanguage,
  DiAndFfi,
  EnumsTuplesSlots,
  ErrorsAndFailables,
  FunctionsAndLambdas,
  GenericsAndVariadics,
  Inheritance,
  MemoryModel,
  ModulesAndZones,
  NullableTypes,
  OperatorsAndCasts,
  OwnershipAndReferences,
  PacksAndImpls,
  PrimitiveTypes,
  ReactivityAndComponents,
  SpecsAndTraits,
  Strings,
  TestingAndTracing,
  VariablesAndBindings,
  ArraysAndCollections,
  CompileTimeExecution,
} from './CurrentLanguage.jsx'
import {
  AlgorithmChapter,
  ConcurrencyStdlibChapter,
  ConvertChapter,
  FunctionalChapter,
  ImportsAndConventions,
  IoChapter,
  MathChapter,
  MemoryChapter,
  ParallelismChapter,
  RandomChapter,
  ResultChapter,
  StandardLibrary,
  StringsAndCharsChapter,
  TraitsChapter,
} from './StandardLibrary.jsx'
import SerializerChapter from './Serializer.jsx'
import TimeChapter from './Time.jsx'
import {
  ContainersOverview,
  DequeChapter,
  ListChapter,
  MapChapter,
  MutableListChapter,
  MutableMapChapter,
  MutableSetChapter,
  QueueChapter,
  SetChapter,
  StackChapter,
  TupleChapter,
} from './Containers.jsx'

export const sections = [
  // ── 1. Current Language ───────────────────────────────────────────
  { id: 'wip-language', number: '1', title: 'Current Language', depth: 0, component: CurrentLanguage },
  { id: 'wip-modules', number: '1.1', title: 'Modules & Imports', depth: 1, component: ModulesAndZones },
  { id: 'wip-variables', number: '1.2', title: 'Variables & Bindings', depth: 1, component: VariablesAndBindings },
  { id: 'wip-primitive-types', number: '1.3', title: 'Primitive Types', depth: 1, component: PrimitiveTypes },
  { id: 'wip-operators', number: '1.4', title: 'Operators & Casts', depth: 1, component: OperatorsAndCasts },
  { id: 'wip-strings', number: '1.5', title: 'Strings', depth: 1, component: Strings },
  { id: 'wip-arrays', number: '1.6', title: 'Arrays & Collection Literals', depth: 1, component: ArraysAndCollections },
  { id: 'wip-control-flow', number: '1.7', title: 'Control Flow', depth: 1, component: ControlFlow },
  { id: 'wip-functions', number: '1.8', title: 'Functions & Lambdas', depth: 1, component: FunctionsAndLambdas },
  { id: 'wip-packs', number: '1.9', title: 'Packs, Impls & Properties', depth: 1, component: PacksAndImpls },
  { id: 'wip-generics', number: '1.10', title: 'Generics & Variadics', depth: 1, component: GenericsAndVariadics },
  { id: 'wip-specs', number: '1.11', title: 'Specs & Traits', depth: 1, component: SpecsAndTraits },
  { id: 'wip-enums', number: '1.12', title: 'Enums, Tuples & Slots', depth: 1, component: EnumsTuplesSlots },
  { id: 'wip-errors', number: '1.13', title: 'Errors & Failable Types', depth: 1, component: ErrorsAndFailables },
  { id: 'wip-nullable', number: '1.14', title: 'Nullable Types', depth: 1, component: NullableTypes },
  { id: 'wip-ownership', number: '1.15', title: 'Ownership & References', depth: 1, component: OwnershipAndReferences },
  { id: 'wip-memory', number: '1.16', title: 'The Memory Model', depth: 1, component: MemoryModel },
  { id: 'wip-ctce', number: '1.17', title: 'Compile-Time Execution', depth: 1, component: CompileTimeExecution },
  { id: 'wip-concurrency', number: '1.18', title: 'Concurrency & Tasks', depth: 1, component: ConcurrencyAndTasks },
  { id: 'wip-reactivity', number: '1.19', title: 'Reactivity & Components', depth: 1, component: ReactivityAndComponents },
  { id: 'wip-inheritance', number: '1.20', title: 'Inheritance (node / leaf)', depth: 1, component: Inheritance },
  { id: 'wip-di-ffi', number: '1.21', title: 'Dependency Injection & FFI', depth: 1, component: DiAndFfi },
  { id: 'wip-testing', number: '1.22', title: 'Testing & Tracing', depth: 1, component: TestingAndTracing },

  // ── 2. Standard Library ───────────────────────────────────────────
  { id: 'wip-stdlib', number: '2', title: 'Standard Library', depth: 0, component: StandardLibrary },
  { id: 'wip-stdlib-conventions', number: '2.1', title: 'Imports & Conventions', depth: 1, component: ImportsAndConventions },
  { id: 'wip-stdlib-io', number: '2.2', title: 'IO', depth: 1, component: IoChapter },
  { id: 'wip-stdlib-convert', number: '2.3', title: 'Convert', depth: 1, component: ConvertChapter },
  { id: 'wip-stdlib-math', number: '2.4', title: 'Math', depth: 1, component: MathChapter },
  { id: 'wip-stdlib-strings', number: '2.5', title: 'Strings & Chars', depth: 1, component: StringsAndCharsChapter },
  { id: 'wip-stdlib-random', number: '2.6', title: 'Random', depth: 1, component: RandomChapter },
  { id: 'wip-stdlib-result', number: '2.7', title: 'Result', depth: 1, component: ResultChapter },
  { id: 'wip-stdlib-functional', number: '2.8', title: 'Functional', depth: 1, component: FunctionalChapter },
  { id: 'wip-stdlib-traits', number: '2.9', title: 'Traits', depth: 1, component: TraitsChapter },
  { id: 'wip-stdlib-algorithm', number: '2.10', title: 'Algorithm', depth: 1, component: AlgorithmChapter },
  { id: 'wip-stdlib-memory', number: '2.11', title: 'Memory', depth: 1, component: MemoryChapter },
  { id: 'wip-stdlib-concurrency', number: '2.12', title: 'Concurrency', depth: 1, component: ConcurrencyStdlibChapter },
  { id: 'wip-stdlib-parallelism', number: '2.13', title: 'Parallelism', depth: 1, component: ParallelismChapter },
  { id: 'wip-containers', number: '2.14', title: 'Containers', depth: 1, component: ContainersOverview },
  { id: 'wip-list', number: '2.14.1', title: 'List', depth: 2, component: ListChapter },
  { id: 'wip-mutable-list', number: '2.14.2', title: 'MutableList', depth: 2, component: MutableListChapter },
  { id: 'wip-map', number: '2.14.3', title: 'Map', depth: 2, component: MapChapter },
  { id: 'wip-mutable-map', number: '2.14.4', title: 'MutableMap', depth: 2, component: MutableMapChapter },
  { id: 'wip-set', number: '2.14.5', title: 'Set', depth: 2, component: SetChapter },
  { id: 'wip-mutable-set', number: '2.14.6', title: 'MutableSet', depth: 2, component: MutableSetChapter },
  { id: 'wip-deque', number: '2.14.7', title: 'Deque', depth: 2, component: DequeChapter },
  { id: 'wip-queue', number: '2.14.8', title: 'Queue', depth: 2, component: QueueChapter },
  { id: 'wip-stack', number: '2.14.9', title: 'Stack', depth: 2, component: StackChapter },
  { id: 'wip-tuple', number: '2.14.10', title: 'Tuple', depth: 2, component: TupleChapter },
  { id: 'wip-serializer', number: '2.15', title: 'Serializer', depth: 1, component: SerializerChapter },
  { id: 'wip-time', number: '2.16', title: 'Time', depth: 1, component: TimeChapter },
]
