import {
  ConcurrencyAndTasks,
  ControlFlow,
  Contracts,
  CurrentLanguage,
  DiAndFfi,
  EnumsTuplesSlots,
  ErrorsAndFailables,
  FunctionsAndLambdas,
  GenericsAndVariadics,
  Inheritance,
  MemoryModel,
  ModulesAndZones,
  NullableTypes,
  OperatorsAndCasts,
  OwnershipAndReferences,
  PacksAndImpls,
  PrimitiveTypes,
  ReactivityAndComponents,
  SpecsAndTraits,
  Strings,
  TestingAndTracing,
  VariablesAndBindings,
  ArraysAndCollections,
  CompileTimeExecution,
} from './CurrentLanguage.jsx'
import {
  AlgorithmChapter,
  ConcurrencyStdlibChapter,
  ConvertChapter,
  FunctionalChapter,
  ImportsAndConventions,
  IoChapter,
  MacroChapter,
  MathChapter,
  MemoryChapter,
  ParallelismChapter,
  RandomChapter,
  ReactiveChapter,
  ReflectionChapter,
  ResultChapter,
  StandardLibrary,
  StringsAndCharsChapter,
  TraitsChapter,
} from './StandardLibrary.jsx'
import SerializerChapter from './Serializer.jsx'
import TimeChapter from './Time.jsx'
import {
  ContainersOverview,
  DequeChapter,
  ListFamily,
  MapFamily,
  QueueChapter,
  SetFamily,
  StackChapter,
  TupleChapter,
} from './Containers.jsx'
import {
  BridgesFfiChapter,
  CompilerInfrastructure,
  CompilerOverviewChapter,
  FrontendChapter,
  InterpreterChapter,
  IrGenerationChapter,
  JavaScriptBackendChapter,
  LlvmBackendChapter,
  PreSemanticChapter,
  SemanticPipelineChapter,
  StdlibInjectionChapter,
  WasmBackendChapter,
} from './CompilerInfrastructure.jsx'

export const sections = [
  // ── 1. Current Language ───────────────────────────────────────────
  { id: 'v004-language', number: '1', title: 'Current Language', depth: 0, component: CurrentLanguage },
  { id: 'v004-modules', number: '1.1', title: 'Modules & Imports', depth: 1, component: ModulesAndZones },
  { id: 'v004-variables', number: '1.2', title: 'Variables & Bindings', depth: 1, component: VariablesAndBindings },
  { id: 'v004-primitive-types', number: '1.3', title: 'Primitive Types', depth: 1, component: PrimitiveTypes },
  { id: 'v004-operators', number: '1.4', title: 'Operators & Casts', depth: 1, component: OperatorsAndCasts },
  { id: 'v004-strings', number: '1.5', title: 'Strings', depth: 1, component: Strings },
  { id: 'v004-arrays', number: '1.6', title: 'Arrays & Collection Literals', depth: 1, component: ArraysAndCollections },
  { id: 'v004-control-flow', number: '1.7', title: 'Control Flow', depth: 1, component: ControlFlow },
  { id: 'v004-functions', number: '1.8', title: 'Functions & Lambdas', depth: 1, component: FunctionsAndLambdas },
  { id: 'v004-packs', number: '1.9', title: 'Packs, Impls & Properties', depth: 1, component: PacksAndImpls },
  { id: 'v004-generics', number: '1.10', title: 'Generics & Variadics', depth: 1, component: GenericsAndVariadics },
  { id: 'v004-specs', number: '1.11', title: 'Specs & Traits', depth: 1, component: SpecsAndTraits },
  { id: 'v004-enums', number: '1.12', title: 'Enums, Tuples & Slots', depth: 1, component: EnumsTuplesSlots },
  { id: 'v004-errors', number: '1.13', title: 'Errors & Failable Types', depth: 1, component: ErrorsAndFailables },
  { id: 'v004-nullable', number: '1.14', title: 'Nullable Types', depth: 1, component: NullableTypes },
  { id: 'v004-ownership', number: '1.15', title: 'Ownership & References', depth: 1, component: OwnershipAndReferences },
  { id: 'v004-memory', number: '1.16', title: 'The Memory Model', depth: 1, component: MemoryModel },
  { id: 'v004-ctce', number: '1.17', title: 'Compile-Time Execution', depth: 1, component: CompileTimeExecution },
  { id: 'v004-contracts', number: '1.18', title: 'Contracts', depth: 1, component: Contracts },
  { id: 'v004-concurrency', number: '1.19', title: 'Concurrency & Tasks', depth: 1, component: ConcurrencyAndTasks },
  { id: 'v004-reactivity', number: '1.20', title: 'Reactivity & Components', depth: 1, component: ReactivityAndComponents },
  { id: 'v004-inheritance', number: '1.21', title: 'Inheritance (node / leaf)', depth: 1, component: Inheritance },
  { id: 'v004-di-ffi', number: '1.22', title: 'Dependency Injection & FFI', depth: 1, component: DiAndFfi },
  { id: 'v004-testing', number: '1.23', title: 'Testing & Tracing', depth: 1, component: TestingAndTracing },

  // ── 2. Standard Library ───────────────────────────────────────────
  { id: 'v004-stdlib', number: '2', title: 'Standard Library', depth: 0, component: StandardLibrary },
  { id: 'v004-stdlib-conventions', number: '2.1', title: 'Imports & Conventions', depth: 1, component: ImportsAndConventions },
  { id: 'v004-stdlib-io', number: '2.2', title: 'IO', depth: 1, component: IoChapter },
  { id: 'v004-stdlib-convert', number: '2.3', title: 'Convert', depth: 1, component: ConvertChapter },
  { id: 'v004-stdlib-math', number: '2.4', title: 'Math', depth: 1, component: MathChapter },
  { id: 'v004-stdlib-strings', number: '2.5', title: 'Strings & Chars', depth: 1, component: StringsAndCharsChapter },
  { id: 'v004-stdlib-random', number: '2.6', title: 'Random', depth: 1, component: RandomChapter },
  { id: 'v004-stdlib-result', number: '2.7', title: 'Result', depth: 1, component: ResultChapter },
  { id: 'v004-stdlib-functional', number: '2.8', title: 'Functional', depth: 1, component: FunctionalChapter },
  { id: 'v004-stdlib-traits', number: '2.9', title: 'Traits', depth: 1, component: TraitsChapter },
  { id: 'v004-stdlib-algorithm', number: '2.10', title: 'Algorithm', depth: 1, component: AlgorithmChapter },
  { id: 'v004-stdlib-memory', number: '2.11', title: 'Memory', depth: 1, component: MemoryChapter },
  { id: 'v004-stdlib-concurrency', number: '2.12', title: 'Concurrency', depth: 1, component: ConcurrencyStdlibChapter },
  { id: 'v004-stdlib-parallelism', number: '2.13', title: 'Parallelism', depth: 1, component: ParallelismChapter },
  { id: 'v004-containers', number: '2.14', title: 'Containers', depth: 1, component: ContainersOverview },
  { id: 'v004-list', number: '2.14.1', title: 'List family', depth: 2, component: ListFamily },
  { id: 'v004-set', number: '2.14.2', title: 'Set family', depth: 2, component: SetFamily },
  { id: 'v004-map', number: '2.14.3', title: 'Map family', depth: 2, component: MapFamily },
  { id: 'v004-deque', number: '2.14.4', title: 'Deque', depth: 2, component: DequeChapter },
  { id: 'v004-queue', number: '2.14.5', title: 'Queue', depth: 2, component: QueueChapter },
  { id: 'v004-stack', number: '2.14.6', title: 'Stack', depth: 2, component: StackChapter },
  { id: 'v004-tuple', number: '2.14.7', title: 'Tuple', depth: 2, component: TupleChapter },
  { id: 'v004-serializer', number: '2.15', title: 'Serializer', depth: 1, component: SerializerChapter },
  { id: 'v004-time', number: '2.16', title: 'Time', depth: 1, component: TimeChapter },
  { id: 'v004-stdlib-macro', number: '2.17', title: 'Macro', depth: 1, component: MacroChapter },
  { id: 'v004-stdlib-reflection', number: '2.18', title: 'Reflection', depth: 1, component: ReflectionChapter },
  { id: 'v004-stdlib-reactive', number: '2.19', title: 'Reactive', depth: 1, component: ReactiveChapter },

  // ── 3. Compiler infrastructure ────────────────────────────────────
  { id: 'v004-compiler', number: '3', title: 'Compiler Infrastructure', depth: 0, component: CompilerInfrastructure },
  { id: 'v004-compiler-overview', number: '3.1', title: 'Overview & Orchestration', depth: 1, component: CompilerOverviewChapter },
  { id: 'v004-compiler-frontend', number: '3.2', title: 'Frontend', depth: 1, component: FrontendChapter },
  { id: 'v004-compiler-presemantic', number: '3.3', title: 'Pre-Semantic Rewrites', depth: 1, component: PreSemanticChapter },
  { id: 'v004-compiler-semantic', number: '3.4', title: 'Semantic Pipeline', depth: 1, component: SemanticPipelineChapter },
  { id: 'v004-compiler-stdlib', number: '3.5', title: 'Standard-Library Injection', depth: 1, component: StdlibInjectionChapter },
  { id: 'v004-compiler-ir', number: '3.6', title: 'IR Generation', depth: 1, component: IrGenerationChapter },
  { id: 'v004-compiler-js', number: '3.7', title: 'JavaScript Backend', depth: 1, component: JavaScriptBackendChapter },
  { id: 'v004-compiler-wasm', number: '3.8', title: 'WebAssembly Backend', depth: 1, component: WasmBackendChapter },
  { id: 'v004-compiler-llvm', number: '3.9', title: 'LLVM Backend', depth: 1, component: LlvmBackendChapter },
  { id: 'v004-compiler-interp', number: '3.10', title: 'Interpreter', depth: 1, component: InterpreterChapter },
  { id: 'v004-compiler-bridges', number: '3.11', title: 'Bridges & FFI', depth: 1, component: BridgesFfiChapter },
]
